# Site
repository: truliii/truliii.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김미진
title: 백엔드 개발자 신입
email: alwls726@naver.com
website: www.github.com/truliii

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: truliii
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_mj.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 항상 겸손한 마음으로 배우는 신입 백엔드 개발자 <mark>김미진</mark>입니다.
  - 정보처리기사 합격 (2023.09)
  - SQLD 합격 (2023.07)
  - TOEIC 890 (2022.08)

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak
        title: 구디아카데미
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: (K-DT)Java 개발자 양성과정
        caption: 2023.04 - 2023.09
        # quote: >
        description: | # this will include new lines to allow paragraphs
          - 교육시간 : 총 118일 / 900시간
          - 교육과정 : 
            - Java, JavaScript, Jquery
            - HTML, CSS, BootStrap
            - JSP, Spring Framework
            - MariaDB, Oracle DB
            - AWS, Docker

      - layout: left
        title: 숙명여자대학교
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 영어영문학부 TESL전공
        caption: 2012.03 - 2018.02
      #   quote: >
      #     TESL(Teaching English as a Second Language)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Cake Craft
        sub_title: |
          MVC 방식의 Spring Boot 기반
          전자결재 시스템 팀 프로젝트
        # link: http://43.202.82.110/cherrymusic/home.jsp
        # link_text: Cake Craft Website
        additional_links:
          - title: Cake Craft
            icon: fab fa-github
            url: github.com/Booyo-Vo/Cake_Craft
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        description: | # this will include new lines to allow paragraphs
          ![CakeCraft](/images/cakecraft_reservation.png "Cake Craft")
          - 기간 : 2023.08.01 ~ 진행 중
          - 인원 : 5명
          - 개발환경 : Java17, JavaScript, Jquery, MariaDB, Tomcat9, Spring Boot
          - 담당역할 :
            - 관리자파트
              - 시설비품관리 : 시설비품 카테고리 등록/수정, jqgrid를 이용한 시설비품 리스트 출력, 시설비품 등록/수정
            - 사용자 파트 
              - 시설비품 예약관리 : 일별 시설비품 예약현황 출력, 시설비품 예약기능, jqgrid를 이용한 사원별 예약 이력 출력, 예약 시간 이전 삭제 기능
              - 메신저(구현중) : 채팅방 등록, WebSocket을 이용한 채팅기능

      - layout: left
        border: weak
        title: Cherry Music
        sub_title: |
          모델1 방식의 JSP기반 
          쇼핑몰 팀 프로젝트
        # link: http://43.202.82.110/cherrymusic/home.jsp
        # link_text: http://43.202.82.110/cherrymusic/home.jsp
        additional_links:
          - title: Cherry Music
            icon: fab fa-github
            url: github.com/truliii/cherry_music
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        description: | # this will include new lines to allow paragraphs
          ![Cherry Music](/images/cherry_music_product.png "Cherry Music")
          - 기간 : 2023.05.30 ~ 2023.06.23
          - 인원 : 3명
          - 개발환경 : Java17, JavaScript, Jquery, MariaDB, Tomcat9
          - 담당역할 : 
            - 관리자파트
              - 주문관리 : 고객 주문리스트 출력, 결제상태 및 배송상태별 검색 기능
              - 리뷰관리 : 고객이 작성한 리뷰 리스트 출력, 리뷰에 대한 관리자 답변 입력/수정/삭제 기능
              - 회원 권한 관리 : 관리자 및 고객 상세정보 출력, 관리자 권한 부여 기능
            - 사용자 파트 
              - 개인정보관리 : 개인정보 수정/조회/삭제, kakao주소 api를 이용한 주소 입력/수정/삭제 기능 , 최근 3개월 내 사용하지 않은 비밀번호로 변경
              - 장바구니 및 주문 : 세션을 활용한 비회원 장바구니 담기, ajax를 이용한 장바구니 수량 변경
              - 리뷰 : 주문한 상품에 대한 리뷰 작성/수정/삭제, cos api를 이용한 이미지 파일 등록
              - 상품 리스트 출력 : 전체/카테고리별 상품 출력

      - layout: left
        #border: weak
        title: JJACK JJACK Cash
        sub_title: |
          모델2 방식의 JSP기반 
          가계부 개인 프로젝트
        # link: http://43.202.82.110/cash/on/cashbook
        # link_text: http://43.202.82.110/cash/on/cashbook
        additional_links:
          - title: JJACK JJACK Cash
            icon: fab fa-github
            url: github.com/truliii/jjackjjack-cash
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        description: | # this will include new lines to allow paragraphs
          ![Cashbook](/images/cashbook_calendar.png "Cashbook")
          - 기간 : 2023.07.01 ~ 2023.07.21
          - 개발환경 : Java17, JavaScript, Jquery, MariaDB, Tomcat9
          - 구현기능 :
            - 로그인
              - Cookie를 이용한 아이디 저장기능
              - Session Filter를 이용한 현재 방문자 수, 오늘 방문자 수, 누적 방문자 수 출력
            - 가계부
              - Calendar api 이용하여 월별 가계부 출력
              - 가계부 입력, 수정, 삭제 기능
              - 입력 시 해시태그 추출하여 해시태그별 내역 출력
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
